title: Conectando os Pontos da IA
longtitle: Conectando os Pontos da IA - Como a Inteligencia Artificial Realmente Funciona e Transforma o Mundo
remote_theme: sighingnow/jekyll-gitbook
description: Seu primeiro passo para um letramento efetivo em Inteligencia Artificial
