title: Conectando os Pontos da IA - Como a Inteligencia Artificial Realmente Funciona e Transforma o Mundo
description: Seu primeiro passo para um letramento efetivo em Inteligencia Artificial
remote_theme: just-the-docs/just-the-docs
color_scheme: light
