title: Conectando os Pontos da IA - Como a Inteligencia Artificial Realmente Funciona e Transforma o Mundo
theme: minima
description: Seu primeiro passo para um letramento efetivo em Inteligencia Artificial
